ALTER TABLE `course` ADD COLUMN `NJBH` VARCHAR(10) DEFAULT NULL COMMENT '年级编号';
ALTER TABLE `course` ADD COLUMN `CHILD_KCXLBH` VARCHAR(20) DEFAULT NULL COMMENT '子课程系列编号';
ALTER TABLE `course` ADD COLUMN `CHILD_KCXLMC` VARCHAR(100) DEFAULT NULL COMMENT '子课程系列名称';
ALTER TABLE `course_xl` ADD COLUMN `PARENT_BH` VARCHAR(20) DEFAULT NULL COMMENT '父节点';
ALTER TABLE `class_register` ADD COLUMN `EMAIL` VARCHAR(30) NOT NULL COMMENT '邮箱';
ALTER TABLE `jyjg_user` ADD COLUMN `EMAIL` VARCHAR(30) NOT NULL COMMENT '邮箱';
